import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface CartAddon {
  addonId: string;
  addonGroupId: string;
  name: string;
  price: number;
}

export interface CartItem {
  cartItemId: string;
  menuItemId: string;
  menuItemName: string;
  menuItemImage: string | null;
  variantId: string;
  variantName: string;
  variantPrice: number;
  finalPrice: number;
  selectedAddons: CartAddon[];
  quantity: number;
  specialInstructions: string;
  itemTotal: number;
}

// The shape a caller passes in — no cartItemId/itemTotal yet,
// since those are derived/generated by the store, not the caller.
type NewCartItem = Omit<CartItem, "cartItemId" | "itemTotal">;

interface CartState {
  items: CartItem[];
  addItem: (item: NewCartItem) => void;
  removeItem: (cartItemId: string) => void;
  updateQuantity: (cartItemId: string, quantity: number) => void;
  clearCart: () => void;
}

function calculateItemTotal(item: NewCartItem): number {
  const addonsTotal = item.selectedAddons.reduce((sum, a) => sum + a.price, 0);
  return (item.finalPrice + addonsTotal) * item.quantity;
}

/**
 * Two cart entries are "the same line" only if the item, variant,
 * addons (same set, order doesn't matter), and instructions all match.
 * Comparing addon sets by sorted id-string is simpler and safer than
 * comparing objects/arrays directly.
 */
function isSameLine(a: NewCartItem, b: CartItem): boolean {
  if (a.menuItemId !== b.menuItemId) return false;
  if (a.variantId !== b.variantId) return false;
  if (a.specialInstructions.trim() !== b.specialInstructions.trim()) return false;

  const aAddonIds = a.selectedAddons.map((x) => x.addonId).sort().join(",");
  const bAddonIds = b.selectedAddons.map((x) => x.addonId).sort().join(",");
  return aAddonIds === bAddonIds;
}

export const useCartStore = create<CartState>()(
  persist(
    (set, get) => ({
      items: [],

      addItem: (newItem) => {
        const existing = get().items.find((item) => isSameLine(newItem, item));

        if (existing) {
          get().updateQuantity(existing.cartItemId, existing.quantity + newItem.quantity);
          return;
        }

        const cartItem: CartItem = {
          ...newItem,
          cartItemId: crypto.randomUUID(),
          itemTotal: calculateItemTotal(newItem),
        };

        set((state) => ({ items: [...state.items, cartItem] }));
      },

      removeItem: (cartItemId) => {
        set((state) => ({
          items: state.items.filter((i) => i.cartItemId !== cartItemId),
        }));
      },

      updateQuantity: (cartItemId, quantity) => {
        if (quantity <= 0) {
          get().removeItem(cartItemId);
          return;
        }
        set((state) => ({
          items: state.items.map((i) =>
            i.cartItemId === cartItemId
              ? { ...i, quantity, itemTotal: calculateItemTotal({ ...i, quantity }) }
              : i
          ),
        }));
      },

      clearCart: () => set({ items: [] }),
    }),
    {
      name: "localbite-cart", // localStorage key
    }
  )
);

// ---------- Derived selectors (never stored, always computed) ----------

export function useCartSubtotal(): number {
  return useCartStore((state) => state.items.reduce((sum, i) => sum + i.itemTotal, 0));
}

export function useCartTotalItems(): number {
  return useCartStore((state) => state.items.reduce((sum, i) => sum + i.quantity, 0));
}